stages:
  - test
  - deploy

default:
  before_script:
    - printf "%sn" "$DEFAULT_CA_CERTS" > /usr/local/share/ca-certificates/cert.crt
    - export NODE_EXTRA_CA_CERTS="/usr/local/share/ca-certificates/cert.crt"
    - export DART_VM_OPTIONS="--root-certs-file=/usr/local/share/ca-certificates/cert.crt"
    - update-ca-certificates -f

test:
  stage: test
  image: ghcr.io/cirruslabs/flutter:3.7.8
  script:
    - flutter test


release:
  stage: deploy
  image: node:latest
  when: on_success
  script:
    - export GITLAB_TOKEN=$BOT_TOKEN
    - export GIT_AUTHOR_NAME=platform-mobile-ci-bot
    - export GIT_COMMITTER_NAME=platform-mobile-ci-bot
    - export GIT_AUTHOR_EMAIL=bot@noreply.ntp-gitlab.krista.ru
    - export GIT_COMMITTER_EMAIL=bot@noreply.ntp-gitlab.krista.ru
    - npm install semantic-release-flutter-plugin -D
    - npm install -D conventional-changelog-conventionalcommits semantic-release/commit-analyzer semantic-release/release-notes-generator semantic-release/changelog semantic-release/git
    - npx -p semantic-release semantic-release --ci
