stages:
  - test
  - deploy

default:
  before_script:
    - printenv
    - mkdir -m 700 "${HOME}/.ssh"
    - ssh-keyscan -p 2222 -H "${CI_SERVER_HOST}" >> ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - tr -d '\r' < "${GIT_PRIVATE_KEY}" | ssh-add -

    - printf "%sn" "$DEFAULT_CA_CERTS" > /usr/local/share/ca-certificates/cert.crt
    - export NODE_EXTRA_CA_CERTS="/usr/local/share/ca-certificates/cert.crt"
    - export DART_VM_OPTIONS="--root-certs-file=/usr/local/share/ca-certificates/cert.crt"
    - update-ca-certificates -f

test:
  stage: test
  image: ghcr.io/cirruslabs/flutter:3.7.8
  script:
    - cp pubspec.yaml pubspec_https.yaml
    - sed -i 's#https://ntp-gitlab.krista.ru/#ssh://git@ntp-gitlab.krista.ru:2222/#g' pubspec.yaml
    - flutter test
    - cp pubspec_https.yaml pubspec.yaml

release:
  stage: deploy
  image: node:latest
  when: on_success
  script:
    - export GITLAB_TOKEN=$BOT_ACCESS_TOKEN
    - export GIT_AUTHOR_NAME=platform-mobile-ci-bot
    - export GIT_COMMITTER_NAME=platform-mobile-ci-bot
    - export GIT_AUTHOR_EMAIL=bot@noreply.ntp-gitlab.krista.ru
    - export GIT_COMMITTER_EMAIL=bot@noreply.ntp-gitlab.krista.ru
    - npm install semantic-release-flutter-plugin -D
    - npm install -D conventional-changelog-conventionalcommits semantic-release/commit-analyzer semantic-release/release-notes-generator semantic-release/changelog semantic-release/git
    - npx -p semantic-release semantic-release --ci
