stages:
  - deploy

default:
  before_script:
    - printf "%sn" "$DEFAULT_CA_CERTS" > /usr/local/share/ca-certificates/cert.crt
    - export NODE_EXTRA_CA_CERTS="/usr/local/share/ca-certificates/cert.crt"
    - export DART_VM_OPTIONS="--root-certs-file=/usr/local/share/ca-certificates/cert.crt"
    - update-ca-certificates -f

release:
  stage: deploy
  image: node:latest
  script:
    - export GITLAB_TOKEN=$BOT_TOKEN
    - export GIT_AUTHOR_NAME=platform-mobile-ci-bot
    - export GIT_COMMITTER_NAME=platform-mobile-ci-bot
    - export GIT_AUTHOR_EMAIL=bot@noreply.ntp-gitlab.krista.ru
    - export GIT_COMMITTER_EMAIL=bot@noreply.ntp-gitlab.krista.ru
    - npm install semantic-release-flutter-plugin -D
    - npm install conventional-changelog-conventionalcommits -D
    - npx -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release --ci
