include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    use_build_context_synchronously: false
    constant_identifier_names: false
    cancel_subscriptions: true
    close_sinks: true
    unnecessary_statements: true
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_returning_this: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    directives_ordering: true
    eol_at_end_of_file: true
    implicit_call_tearoffs: true
    join_return_with_assignment: true
    no_runtimeType_toString: true
    noop_primitive_operations: true
    one_member_abstracts: true
    parameter_assignments: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_null_aware_method_calls: true
    require_trailing_commas: true
    sized_box_shrink_expand: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    type_annotate_public_apis: true
    unnecessary_await_in_return: true
    unnecessary_to_list_in_spreads: true
    use_full_hex_values_for_flutter_colors: true
    use_super_parameters: true
    prefer_constructors_over_static_methods: true
    avoid_catches_without_on_clauses: true
    always_put_required_named_parameters_first: true
    sized_box_for_whitespace: true
    library_private_types_in_public_api: false
    # always_specify_types: true
