include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - lib/utils/X509Certificate/*
    - 'example/**'

linter:
  rules:
    constant_identifier_names: false
    prefer_constructors_over_static_methods: false
    prefer_final_locals: false
    avoid_classes_with_only_static_members: false
    use_build_context_synchronously: false
    sort_pub_dependencies: false
    curly_braces_in_flow_control_structures: false
    unnecessary_this: false
    library_private_types_in_public_api: false
    non_constant_identifier_names: false