/// Flutter icons CryptSignatureIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CryptSignatureIcons
///      fonts:
///       - asset: fonts/CryptSignatureIcons.ttf
///
///
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class CryptSignatureIcons {
  CryptSignatureIcons._();

  static const _kFontFam = 'CryptSignatureIcons';
  static const String _kFontPkg = 'crypt_signature';

  static const IconData license = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark_cicle = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_circle = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
